define({
    root:({
        error: "Error",
        errorChoosingMeasureOnMap: "An error occurred while querying for the measure.",
        errorChoosingRouteOnMap: "An error occurred while querying for the route.",
        errorGettingLrsLayers: "An error occurred while trying to get the LRS information.",
        errorValidatingRoute: "An error occurred while trying to validate the route.",
        fromMeasure: "From Measure",
        fromMeasureWithUnits: "From Measure (${0})",
        fromRouteId: "From Route ID",
        fromRouteName: "From Route Name",
        invalidMeasure: "The measure is invalid. Please enter a valid number.",
        invalidRoute: "Please enter a valid route.",
        invalidRouteId: "Please enter a valid route ID.",
        invalidRouteName: "Please enter a valid route name.",
        invalidRouteOnLine: "From route and to route must be on the same line.",
        measureNotLocated: "The measure could not be located on the selected route.",
        network: "Network",
        noAuthorizedLrsServiceDetected: "You are not authorized to access the linear referencing map service. Please notify the application administrator.",
        noLrsServiceDetected: "No linear referencing service was detected in the map.",
        nullValue: "&lt;null&gt;",
        routeId: "Route ID",
        routeName: "Route Name",
        selectFeaturePopup_defaultLabel: "Feature:",
        selectFeaturePopup_defaultMessage: "Please select the desired feature from the list below.",
        selectFeaturePopup_defaultTitle: "You have selected ${0} features.",
        selectFeaturePopup_lineLabel: "Line:",
        selectFeaturePopup_lineMessage: "Please select the desired line from the list below.",
        selectFeaturePopup_lineTitle: "You have selected ${0} lines.",
        selectFeaturePopup_noFeatureId: "No ID",
        selectFeaturePopup_routeLabel: "Route:",
        selectFeaturePopup_routeMessage: "Please select the desired route from the list below.",
        selectFeaturePopup_routeTitle: "You have selected ${0} routes.",
        selectFeaturePopup_selectLabel: "select",
        selectFeaturePopup_viewLabel: "show",
        selectFeaturePopup_viewTooltip: "flash on map",
        selectMeasureTooltip: "Select a measure on the map",
        selectMeasureDrawTooltip: "Click to select a measure",
        selectRouteTooltip: "Select a route on the map",
        selectRouteDrawTooltip: "Click to select a route",
        toMeasure: "To Measure",
        toMeasureWithUnits: "To Measure (${0})",
        toRouteId: "To Route ID",
        toRouteName: "To Route Name",
        tooManyEditWorkspacesDetected: "More than one editing workspace was detected in the linear referencing service. This widget supports only one editing workspace for all event layers in the map.",
        tooManyLrsServicesDetected: "More than one linear referencing service was detected in the map description. This widget only supports one linear referencing service in the map.",
        useRouteEnd: "Use the route end",
        useRouteStart: "Use the route start",
        useRouteStartEndGeometryError: "Please enter a valid route with a geometry.",
        useRouteStartEndRouteError: "Please enter a valid route.",
        
        
        //units
        unknownUnits: "Unknown Units",
        esriUnknownUnits: "Unknown Units",
        points: "Points",
        esriPoints: "Points",
        inches: "Inches",
        esriInches: "Inches",
        feet: "Feet",
        esriFeet: "Feet",
        yards: "Yards",
        esriYards: "Yards",
        miles: "Miles",
        esriMiles: "Miles",
        nauticalMiles: "Nautical Miles",
        esriNauticalMiles: "Nautical Miles",
        millimeters: "Millimeters",
        esriMillimeters: "Millimeters",
        centimeters: "Centimeters",
        esriCentimeters: "Centimeters",
        decimeters: "Decimeters",
        esriDecimeters: "Decimeters",
        meters: "Meters",
        esriMeters: "Meters",
        kilometers: "Kilometers",
        esriKilometers: "Kilometers",
        decimalDegrees: "Decimal Degrees",
        esriDecimalDegrees: "Decimal Degrees"
    }) 
});